-- Exercice DML2

--2.1
SELECT a.CODE_ART,c.NOM_CAT
FROM TARTICLE a
INNER JOIN TCATEGORIE c on a.FKCATEGORIE_ART = c.CODE_CAT
WHERE c.CODE_CAT in ('V','VR','VB')

--2.2
SELECT c.NUM_COM,c.TOTAL_COM,s.NOM_SER ||' '||s.PRENOM_SER
FROM TCOMMANDE c 
INNER JOIN TSERVEUR s on c.FKSERVEUR_COM = s.CODE_SER
WHERE c.ETAT_COM in('PAYEE')
ORDER BY s.NOM_SER


--2.3
SELECT a.CODE_ART,a.PRIX_ART,COALESCE(c.NOM_CAT,'Autre' )as CATEGORIE
FROM TARTICLE a
LEFT JOIN TCATEGORIE c on a.FKCATEGORIE_ART = c.CODE_CAT
WHERE a.PRIX_ART < 20 and a.FKETAPE_ART in ('P') 
ORDER BY a.PRIX_ART

--2.4
SELECT a.CODE_ART
FROM TARTICLE a
LEFT JOIN TLIGNECMD l on l.FKARTICLE_LIG = a.CODE_ART
WHERE a.FKETAPE_ART='E' and l.FKCOMMANDE_LIG is null


--2.6
SELECT c.FKSERVEUR_COM as serveur, l.FKCOMMANDE_LIG as commande,
 l.NUM_LIG, a.NOM_ART, l.PRIX_LIG, cat.NOM_CAT
 FROM TCOMMANDE c
INNER JOIN TLIGNECMD l on l.FKCOMMANDE_LIG = c.NUM_COM
INNER JOIN TARTICLE a on l.FKARTICLE_LIG = a.CODE_ART
LEFT JOIN TCATEGORIE cat on a.FKCATEGORIE_ART=cat.CODE_CAT 
WHERE l.ETAT_LIG ='SERVI'
ORDER BY l.FKCOMMANDE_LIG,l.NUM_LIG
