--DML1

--1
SELECT *
FROM TLIGNECMD l 
ORDER BY l.FKCOMMANDE_LIG, l.NUM_LIG

--2
select c.CODE_CAT,c.NOM_CAT
FROM TCATEGORIE c
WHERE c.CODE_CAT LIKE '_ %'

--3
SELECT a.CODE_ART,a.NOM_ART,a.FKCATEGORIE_ART
FROM TARTICLE a
WHERE a.FKCATEGORIE_ART like 'B_%'
ORDER BY a.FKCATEGORIE_ART

--4
SELECT a.NOM_ART,a.CALORIE_ART
FROM TARTICLE a
WHERE a.CALORIE_ART < 100 and a.FKETAPE_ART = 'E'

--5
SELECT CURRENT_DATE as "DATE", CURRENT_TIME as TEMPS
FROM RDB$DATABASE

--6
SELECT FIRST 10 SKIP 112 *
FROM TCPVILLE v

SELECT *
FROM TCPVILLE v ROWS 113 to 122

--------1.6.3
SELECT FIRST 5 SKIP (2903/2) *
FROM TCPVILLE 

--7
SELECT a.CODE_ART,a.NOM_ART,a.DESCRIPTION_ART
FROM TARTICLE a 
WHERE a.DESCRIPTION_ART CONTAINING ('''')

--8
SELECT  EXTRACT (DAY FROM CURRENT_DATE) as jour,
        EXTRACT (MONTH FROM CURRENT_DATE) as mois,
        EXTRACT (YEAR FROM CURRENT_DATE) as annee
FROM RDB$DATABASE

--9
SELECT CAST((1+SQRT(5))/2 as DECIMAL (10,8)) as "Nombred'or"
FROM RDB$DATABASE

--10
SELECT l.FKARTICLE_LIG, CAST(l.MOMENT_LIG as TIME) as HEURE
FROM TLIGNECMD l
WHERE l.FKCOMMANDE_LIG = 1

--11
SELECT COUNT(*)
FROM TCPVILLE
WHERE cp_cpv CONTAINING 3700

--12
SELECT DISTINCT l.FKARTICLE_LIG
FROM TLIGNECMD l
WHERE l.ETAT_LIG not in ('erreur','annule')

--13
SELECT v.CP_CPV 
FROM TCPVILLE v
WHERE v.CP_CPV in (1030,1040,1050,1150,1160)

--14
SELECT v.VILLE_CPV 
FROM TCPVILLE v
WHERE v.CP_CPV in (1030,1040,1050,1150,1160) and v.VILLE_CPV CONTAINING 'Bruxelles'

--15
SELECT v.cp_cpv,
       TRIM(TRAILING ')' FROM 
       TRIM(LEADING 'Bruxelles (' FROM v.VILLE_CPV))
FROM TCPVILLE v
WHERE v.CP_CPV IN (1030, 1040, 1050, 1150, 1160) AND v.VILLE_CPV STARTING WITH 'Brux';

--16
SELECT v.cp_cpv,
       TRIM(TRAILING ')' FROM 
       TRIM(LEADING 'Bruxelles (' FROM v.VILLE_CPV))
FROM TCPVILLE v
WHERE v.CP_CPV < 1211 AND v.VILLE_CPV STARTING WITH 'Brux';

--17
SELECT DISTINCT v.CP_CPV
FROM TCPVILLE v 
WHERE v.CP_CPV <1300 AND (RIGHT(v.CP_CPV,1)=0 OR v.CP_CPV BETWEEN 1081 AND 1083)
                     AND (v.CP_CPV NOT IN (1010,1100,1110))













