--Corrections DML3
--3.1
SELECT COUNT(*) as NB_ARTICLES FROM TARTICLE a
--3.2
SELECT a.FKCATEGORIE_ART,count(*) as NB_ARTICLES FROM TARTICLE a 
GROUP BY a.FKCATEGORIE_ART
--3.3
SELECT l.FKCOMMANDE_LIG,sum(l.PRIX_LIG) as Total 
FROM TLIGNECMD l
WHERE l.ETAT_LIG='SERVI'
GROUP BY l.FKCOMMANDE_LIG
--3.4
SELECT e.NOM_ETA as etape,
List(trim(a.CODE_ART),' -- ') as choix FROM TARTICLE a 
INNER JOIN TETAPE e on a.FKETAPE_ART=e.CODE_ETA
GROUP BY e.NOM_ETA
--3.4 v2
SELECT decode(a.FKETAPE_ART,'E','Entrée','P','Plat','Dessert') as etape,
List(trim(a.CODE_ART),' -- ') as choix FROM TARTICLE a 
WHERE a.FKETAPE_ART is not null
GROUP BY etape
--3.5
SELECT a.FKETAPE_ART as etape,a.FKCATEGORIE_ART as categorie,
Min(a.PRIX_ART) as prixmin, max(a.PRIX_ART)as prixmax 
FROM TARTICLE a
WHERE a.FKETAPE_ART is not NULL
GROUP BY a.FKETAPE_ART,a.FKCATEGORIE_ART
--3.6
SELECT l.FKCOMMANDE_LIG,count(*) as nblignes
, COUNT(DISTINCT l.FKARTICLE_LIG ) as nbarticles FROM TCOMMANDE c 
INNER JOIN TLIGNECMD l on l.FKCOMMANDE_LIG=c.NUM_COM
WHERE c.ETAT_COM='PAYEE' and l.ETAT_LIG='SERVI'
GROUP by l.FKCOMMANDE_LIG
--3.7
SELECT l.FKCOMMANDE_LIG as cmd, count(*) as nblignes FROM TLIGNECMD l
WHERE l.ETAT_LIG='SERVI'
GROUP BY l.FKCOMMANDE_LIG
HAVING count(*)>8