CREATE TABLE TPAIEMENT (
NUM_PAI INTEGER PRIMARY KEY,
MOMENT_PAI TIMESTAMP DEFAULT LOCALTIMESTAMP
MONTANT_PAI DECIMAL (4,2) NOT NULL,
TYPE_PAI VARCHAR(15) CHECK (TYPE_PAI (IN 'CarteCr�dit', 'CarteD�bit','Esp�ce')), 
FKCOMMANDE_PAI INTEGER NOT NULL REFERENCES TCOMMANDE ON UPDATE CASCADE
);

CREATE Domaines DTypePaiement VARCHAR (15) CHECK (VAlUE (IN 'CarteCr�dit', 'CarteD�bit','Esp�ce'));

ALTER TABLE TLIGNECMD ADD FKPAIEMENT_LIG INT REFERENCES TPAIEMENT on UPDATE CASCADE

INSERT INTO TPAIEMENT (NUM_PAI,MOMENT_PAI,MONTANT_PAI,TYPE_PAI,FKCOMMANDE_PAI)
VALUES (1,LOCALTIMESTAMP,69,'CarteCr�dit',1);

UPDATE TLIGNECMD
SET FKPAIEMENT_LIG = 1
WHERE FKCOMMANDE_LIG = 1

INSERT INTO TPAIEMENT (NUM_PAI,MOMENT_PAI,MONTANT_PAI,TYPE_PAI,FKCOMMANDE_PAI)
VALUES (2,LOCALTIMESTAMP,62.75,'Esp�ce',2);

UPDATE TLIGNECMD
SET FKPAIEMENT_LIG = 2
WHERE FKCOMMANDE_LIG = 2
and NUM_LIG in (1,2,3,4,7);

INSERT INTO TPAIEMENT (NUM_PAI,MOMENT_PAI,MONTANT_PAI,TYPE_PAI,FKCOMMANDE_PAI)
VALUES (3,LOCALTIMESTAMP,78,'Esp�ce',2);

UPDATE TLIGNECMD
SET FKPAIEMENT_LIG = 3
WHERE FKCOMMANDE_LIG = 2
and NUM_LIG NOT in (1,2,3,4,7);






