-- Premier paiement
INSERT INTO TPAIEMENT (NUM_PAI,MOMENT_PAI,MONTANT_PAI,TYPE_PAI,FKCOMMANDE_PAI)
VALUES (1,LOCALTIMESTAMP,69,'CarteCr�dit',1);

UPDATE TLIGNECMD
SET FKPAIEMENT_LIG = 1
WHERE FKCOMMANDE_LIG = 1

-- Deuxieme paiement
INSERT INTO TPAIEMENT (NUM_PAI,MOMENT_PAI,MONTANT_PAI,TYPE_PAI,FKCOMMANDE_PAI)
VALUES (2,LOCALTIMESTAMP,62.75,'Esp�ce',2);

UPDATE TLIGNECMD
SET FKPAIEMENT_LIG = 2
WHERE FKCOMMANDE_LIG = 2
and NUM_LIG in (1,2,3,4,7);

-- Troisieme paiement
INSERT INTO TPAIEMENT (NUM_PAI,MOMENT_PAI,MONTANT_PAI,TYPE_PAI,FKCOMMANDE_PAI)
VALUES (3,LOCALTIMESTAMP,78,'Esp�ce',2);

UPDATE TLIGNECMD
SET FKPAIEMENT_LIG = 3
WHERE FKCOMMANDE_LIG = 2
and NUM_LIG NOT in (1,2,3,4,7);