CREATE TABLE TPAIEMENT (
NUM_PAI INTEGER PRIMARY KEY,
MOMENT_PAI TIMESTAMP DEFAULT LOCALTIMESTAMP
MONTANT_PAI DECIMAL (4,2) NOT NULL,
TYPE_PAI VARCHAR(15) CHECK (TYPE_PAI (IN 'CarteCr�dit', 'CarteD�bit','Esp�ce')), 
FKCOMMANDE_PAI INTEGER NOT NULL REFERENCES TCOMMANDE ON UPDATE CASCADE
);